services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AOE\HappyFeet\:
        resource: '../Classes/*'

    AOE\HappyFeet\Typo3\Hook\LinkRenderer:

    AOE\HappyFeet\Typo3\Hook\Tcemain:

    AOE\HappyFeet\Service\RenderingService:

    AOE\HappyFeet\Domain\Repository\FootnoteRepository:

    AOE\HappyFeet\Typo3\Hook\HappyFeetLinkWizzard:
        public: true