name: Tests

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        typo3: [ ^11.5, ^12.4 ]
        php: [ '8.0', '8.1', '8.2', '8.3' ]
        mysql: [ '5.7' ]
        exclude:
          - typo3: '^12.4'
            php: '8.0'

    steps:
      - name: Set up MySQL ${{ matrix.mysql }}
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.mysql }}
          mysql root password: 'root'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Set up PHP Version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Environment Check
        run: |
          php --version
          composer --version

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require --dev typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json
          ln -nfs .Build/vendor/typo3/cms/typo3 typo3

      - name: Lint PHP
        run: find . -name \*.php ! -path "./.Build/*" ! -path "./scripts/*" ! -path "./typo3_src/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

      - name: Unit Tests without coverage
        if: matrix.typo3 != '^11.5' || matrix.php != '8.3'
        run: |
          export "UNIT_XML"=.Build/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml
          .Build/bin/phpunit --colors -c $UNIT_XML Tests/Unit

      - name: Unit Tests with coverage
        if: matrix.typo3 == '^12.4' && matrix.php == '8.3'
        run: |
          export "UNIT_XML"=.Build/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml
          .Build/bin/phpunit --coverage-filter=Classes --coverage-clover=unittest-coverage.clover --colors -c $UNIT_XML Tests/Unit/

      - name: Functional Tests without coverage
        run: |
          export "FUNCTIONAL_XML"=.Build/vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml
          .Build/bin/phpunit --colors -c $FUNCTIONAL_XML Tests/Functional
        if: matrix.typo3 != '^12.4' || matrix.php != '8.3'
        env:
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseName: typo3
          typo3DatabasePassword: root
          typo3DatabaseUsername: root

      - name: Functional Tests with coverage
        run: |
          export "FUNCTIONAL_XML"=.Build/vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml
          find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --coverage-filter=Classes --coverage-clover={}functionaltest-coverage.clover --colors -c $FUNCTIONAL_XML {}'
        if: matrix.typo3 == '^12.4' && matrix.php == '8.3'
        env:
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseName: typo3
          typo3DatabasePassword: root
          typo3DatabaseUsername: root

      - name: Upload functional coverage results to Scrutinizer
        uses: sudo-bot/action-scrutinizer@latest
        if: matrix.typo3 == '^12.4' && matrix.php == '8.3'
        with:
          cli-args: "--format=php-clover functional-coverage.clover --revision=${{ github.event.pull_request.head.sha || github.sha }}"

      - name: Upload unit coverage results to Scrutinizer
        uses: sudo-bot/action-scrutinizer@latest
        if: matrix.typo3 == '^12.4' && matrix.php == '8.3'
        with:
          cli-args: "--format=php-clover unittest-coverage.clover --revision=${{ github.event.pull_request.head.sha || github.sha }}"
